# Generated by Django 4.2.5 on 2023-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
